[package]
name = "spotify-badge"
version = "0.1.0"
authors = ["Joosung Park <admin@slowmotion.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
